"""empty message

Revision ID: 0683f20977cf
Revises: 
Create Date: 2022-07-30 17:36:47.060414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0683f20977cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('cm_id', sa.String(length=256), nullable=False),
    sa.Column('proj_id', sa.String(length=256), nullable=False),
    sa.Column('owner_uid', sa.String(length=256), nullable=False),
    sa.Column('target_uid', sa.String(length=256), nullable=True),
    sa.Column('parent_id', sa.String(length=256), nullable=True),
    sa.Column('root_id', sa.String(length=256), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cm_id')
    )
    op.create_table('course_user',
    sa.Column('cu_id', sa.String(length=256), nullable=False),
    sa.Column('cid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cu_id')
    )
    op.create_table('courses',
    sa.Column('cid', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('public', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('files',
    sa.Column('fid', sa.String(length=256), nullable=False),
    sa.Column('proj_id', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('file_name', sa.String(length=120), nullable=False),
    sa.Column('file_url', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('messages',
    sa.Column('msg_id', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('read', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('projects',
    sa.Column('proj_id', sa.String(length=256), nullable=False),
    sa.Column('cid', sa.String(length=256), nullable=False),
    sa.Column('aid', sa.String(length=256), nullable=False),
    sa.Column('pid', sa.String(length=256), nullable=False),
    sa.Column('proj_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('max_num', sa.Integer(), nullable=False),
    sa.Column('cur_num', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('proj_id'),
    sa.UniqueConstraint('proj_id'),
    sa.UniqueConstraint('proj_name')
    )
    op.create_table('requirements',
    sa.Column('rid', sa.String(length=256), nullable=False),
    sa.Column('cid', sa.String(length=256), nullable=False),
    sa.Column('aid', sa.String(length=256), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('selections',
    sa.Column('sel_id', sa.String(length=256), nullable=False),
    sa.Column('proj_id', sa.String(length=256), nullable=False),
    sa.Column('sid', sa.String(length=256), nullable=False),
    sa.Column('a_feedback', sa.TEXT(), nullable=False),
    sa.Column('p_feedback', sa.TEXT(), nullable=False),
    sa.Column('award', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sel_id')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('selections')
    op.drop_table('requirements')
    op.drop_table('projects')
    op.drop_table('messages')
    op.drop_table('files')
    op.drop_table('courses')
    op.drop_table('course_user')
    op.drop_table('comments')
    # ### end Alembic commands ###
