"""empty message

Revision ID: 1b35d5569908
Revises: 5563092e3665
Create Date: 2022-08-02 13:37:34.147222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b35d5569908'
down_revision = '5563092e3665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('selections', 'a_feedback',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('selections', 'p_feedback',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('selections', 'p_feedback',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('selections', 'a_feedback',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
