"""empty message

Revision ID: 1e8fa6a0e3cb
Revises: cf6c5101705d
Create Date: 2022-07-17 07:14:46.902246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e8fa6a0e3cb'
down_revision = 'cf6c5101705d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('cm_id', sa.String(length=256), nullable=False),
    sa.Column('proj_id', sa.String(length=256), nullable=False),
    sa.Column('owner_uid', sa.String(length=256), nullable=False),
    sa.Column('target_uid', sa.String(length=256), nullable=False),
    sa.Column('parent_id', sa.String(length=256), nullable=False),
    sa.Column('root_id', sa.String(length=256), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cm_id')
    )
    op.create_table('files',
    sa.Column('fid', sa.String(length=256), nullable=False),
    sa.Column('proj_id', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('file_name', sa.String(length=120), nullable=False),
    sa.Column('file_url', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('messages',
    sa.Column('msg_id', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('read', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('projects',
    sa.Column('proj_id', sa.String(length=256), nullable=False),
    sa.Column('cid', sa.String(length=256), nullable=False),
    sa.Column('aid', sa.String(length=256), nullable=False),
    sa.Column('pid', sa.String(length=256), nullable=False),
    sa.Column('proj_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('max_num', sa.Integer(), nullable=False),
    sa.Column('cur_num', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('proj_id'),
    sa.UniqueConstraint('proj_id'),
    sa.UniqueConstraint('proj_name')
    )
    op.create_table('requirements',
    sa.Column('rid', sa.String(length=256), nullable=False),
    sa.Column('cid', sa.String(length=256), nullable=False),
    sa.Column('aid', sa.String(length=256), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('selections',
    sa.Column('sel_id', sa.String(length=256), nullable=False),
    sa.Column('proj_id', sa.String(length=256), nullable=False),
    sa.Column('sid', sa.String(length=256), nullable=False),
    sa.Column('a_feedback', sa.TEXT(), nullable=False),
    sa.Column('p_feedback', sa.TEXT(), nullable=False),
    sa.Column('award', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('sel_id')
    )
    op.add_column('course_user', sa.Column('cu_id', sa.String(length=256), nullable=False))
    op.drop_column('course_user', 'cuid')
    op.alter_column('courses', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('users', 'detail',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'detail',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('courses', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.add_column('course_user', sa.Column('cuid', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('course_user', 'cu_id')
    op.drop_table('selections')
    op.drop_table('requirements')
    op.drop_table('projects')
    op.drop_table('messages')
    op.drop_table('files')
    op.drop_table('comments')
    # ### end Alembic commands ###
