"""empty message

Revision ID: cf6c5101705d
Revises: 
Create Date: 2022-07-15 04:45:41.146541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6c5101705d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_user',
    sa.Column('cuid', sa.String(length=256), nullable=False),
    sa.Column('cid', sa.String(length=256), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cuid')
    )
    op.create_table('courses',
    sa.Column('cid', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('public', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('utime', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('courses')
    op.drop_table('course_user')
    # ### end Alembic commands ###
