"""empty message

Revision ID: f6a1d94711db
Revises: 
Create Date: 2022-08-04 00:37:28.062488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6a1d94711db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('rid', sa.String(length=256), nullable=False))
    op.alter_column('selections', 'a_feedback',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('selections', 'p_feedback',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('selections', 'p_feedback',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('selections', 'a_feedback',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('projects', 'rid')
    # ### end Alembic commands ###
